// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: super.proto

#ifndef PROTOBUF_super_2eproto__INCLUDED
#define PROTOBUF_super_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace PrivateProto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_super_2eproto();
void protobuf_AssignDesc_super_2eproto();
void protobuf_ShutdownFile_super_2eproto();

class ZoneActiveInfo;
class RegVerifiedAccountToGateway;
class ZoneGatewayReady;

// ===================================================================

class ZoneActiveInfo : public ::google::protobuf::Message {
 public:
  ZoneActiveInfo();
  virtual ~ZoneActiveInfo();

  ZoneActiveInfo(const ZoneActiveInfo& from);

  inline ZoneActiveInfo& operator=(const ZoneActiveInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZoneActiveInfo& default_instance();

  void Swap(ZoneActiveInfo* other);

  // implements Message ----------------------------------------------

  inline ZoneActiveInfo* New() const { return New(NULL); }

  ZoneActiveInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ZoneActiveInfo& from);
  void MergeFrom(const ZoneActiveInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ZoneActiveInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 player_load_reserve = 1;
  inline bool has_player_load_reserve() const;
  inline void clear_player_load_reserve();
  static const int kPlayerLoadReserveFieldNumber = 1;
  inline ::google::protobuf::uint32 player_load_reserve() const;
  inline void set_player_load_reserve(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:PrivateProto.ZoneActiveInfo)
 private:
  inline void set_has_player_load_reserve();
  inline void clear_has_player_load_reserve();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 player_load_reserve_;
  friend void  protobuf_AddDesc_super_2eproto();
  friend void protobuf_AssignDesc_super_2eproto();
  friend void protobuf_ShutdownFile_super_2eproto();

  void InitAsDefaultInstance();
  static ZoneActiveInfo* default_instance_;
};
// -------------------------------------------------------------------

class RegVerifiedAccountToGateway : public ::google::protobuf::Message {
 public:
  RegVerifiedAccountToGateway();
  virtual ~RegVerifiedAccountToGateway();

  RegVerifiedAccountToGateway(const RegVerifiedAccountToGateway& from);

  inline RegVerifiedAccountToGateway& operator=(const RegVerifiedAccountToGateway& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegVerifiedAccountToGateway& default_instance();

  void Swap(RegVerifiedAccountToGateway* other);

  // implements Message ----------------------------------------------

  inline RegVerifiedAccountToGateway* New() const { return New(NULL); }

  RegVerifiedAccountToGateway* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegVerifiedAccountToGateway& from);
  void MergeFrom(const RegVerifiedAccountToGateway& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RegVerifiedAccountToGateway* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 acc_id = 1;
  inline bool has_acc_id() const;
  inline void clear_acc_id();
  static const int kAccIdFieldNumber = 1;
  inline ::google::protobuf::uint64 acc_id() const;
  inline void set_acc_id(::google::protobuf::uint64 value);

  // required uint64 login_id_super = 2;
  inline bool has_login_id_super() const;
  inline void clear_login_id_super();
  static const int kLoginIdSuperFieldNumber = 2;
  inline ::google::protobuf::uint64 login_id_super() const;
  inline void set_login_id_super(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:PrivateProto.RegVerifiedAccountToGateway)
 private:
  inline void set_has_acc_id();
  inline void clear_has_acc_id();
  inline void set_has_login_id_super();
  inline void clear_has_login_id_super();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 acc_id_;
  ::google::protobuf::uint64 login_id_super_;
  friend void  protobuf_AddDesc_super_2eproto();
  friend void protobuf_AssignDesc_super_2eproto();
  friend void protobuf_ShutdownFile_super_2eproto();

  void InitAsDefaultInstance();
  static RegVerifiedAccountToGateway* default_instance_;
};
// -------------------------------------------------------------------

class ZoneGatewayReady : public ::google::protobuf::Message {
 public:
  ZoneGatewayReady();
  virtual ~ZoneGatewayReady();

  ZoneGatewayReady(const ZoneGatewayReady& from);

  inline ZoneGatewayReady& operator=(const ZoneGatewayReady& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZoneGatewayReady& default_instance();

  void Swap(ZoneGatewayReady* other);

  // implements Message ----------------------------------------------

  inline ZoneGatewayReady* New() const { return New(NULL); }

  ZoneGatewayReady* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ZoneGatewayReady& from);
  void MergeFrom(const ZoneGatewayReady& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ZoneGatewayReady* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 acc_id = 1;
  inline bool has_acc_id() const;
  inline void clear_acc_id();
  static const int kAccIdFieldNumber = 1;
  inline ::google::protobuf::uint64 acc_id() const;
  inline void set_acc_id(::google::protobuf::uint64 value);

  // required uint64 login_id_super = 2;
  inline bool has_login_id_super() const;
  inline void clear_login_id_super();
  static const int kLoginIdSuperFieldNumber = 2;
  inline ::google::protobuf::uint64 login_id_super() const;
  inline void set_login_id_super(::google::protobuf::uint64 value);

  // required uint64 token = 3;
  inline bool has_token() const;
  inline void clear_token();
  static const int kTokenFieldNumber = 3;
  inline ::google::protobuf::uint64 token() const;
  inline void set_token(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:PrivateProto.ZoneGatewayReady)
 private:
  inline void set_has_acc_id();
  inline void clear_has_acc_id();
  inline void set_has_login_id_super();
  inline void clear_has_login_id_super();
  inline void set_has_token();
  inline void clear_has_token();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 acc_id_;
  ::google::protobuf::uint64 login_id_super_;
  ::google::protobuf::uint64 token_;
  friend void  protobuf_AddDesc_super_2eproto();
  friend void protobuf_AssignDesc_super_2eproto();
  friend void protobuf_ShutdownFile_super_2eproto();

  void InitAsDefaultInstance();
  static ZoneGatewayReady* default_instance_;
};
// ===================================================================


// ===================================================================

// ZoneActiveInfo

// required uint32 player_load_reserve = 1;
inline bool ZoneActiveInfo::has_player_load_reserve() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ZoneActiveInfo::set_has_player_load_reserve() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ZoneActiveInfo::clear_has_player_load_reserve() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ZoneActiveInfo::clear_player_load_reserve() {
  player_load_reserve_ = 0u;
  clear_has_player_load_reserve();
}
inline ::google::protobuf::uint32 ZoneActiveInfo::player_load_reserve() const {
  // @@protoc_insertion_point(field_get:PrivateProto.ZoneActiveInfo.player_load_reserve)
  return player_load_reserve_;
}
inline void ZoneActiveInfo::set_player_load_reserve(::google::protobuf::uint32 value) {
  set_has_player_load_reserve();
  player_load_reserve_ = value;
  // @@protoc_insertion_point(field_set:PrivateProto.ZoneActiveInfo.player_load_reserve)
}

// -------------------------------------------------------------------

// RegVerifiedAccountToGateway

// required uint64 acc_id = 1;
inline bool RegVerifiedAccountToGateway::has_acc_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegVerifiedAccountToGateway::set_has_acc_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegVerifiedAccountToGateway::clear_has_acc_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegVerifiedAccountToGateway::clear_acc_id() {
  acc_id_ = GOOGLE_ULONGLONG(0);
  clear_has_acc_id();
}
inline ::google::protobuf::uint64 RegVerifiedAccountToGateway::acc_id() const {
  // @@protoc_insertion_point(field_get:PrivateProto.RegVerifiedAccountToGateway.acc_id)
  return acc_id_;
}
inline void RegVerifiedAccountToGateway::set_acc_id(::google::protobuf::uint64 value) {
  set_has_acc_id();
  acc_id_ = value;
  // @@protoc_insertion_point(field_set:PrivateProto.RegVerifiedAccountToGateway.acc_id)
}

// required uint64 login_id_super = 2;
inline bool RegVerifiedAccountToGateway::has_login_id_super() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegVerifiedAccountToGateway::set_has_login_id_super() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegVerifiedAccountToGateway::clear_has_login_id_super() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegVerifiedAccountToGateway::clear_login_id_super() {
  login_id_super_ = GOOGLE_ULONGLONG(0);
  clear_has_login_id_super();
}
inline ::google::protobuf::uint64 RegVerifiedAccountToGateway::login_id_super() const {
  // @@protoc_insertion_point(field_get:PrivateProto.RegVerifiedAccountToGateway.login_id_super)
  return login_id_super_;
}
inline void RegVerifiedAccountToGateway::set_login_id_super(::google::protobuf::uint64 value) {
  set_has_login_id_super();
  login_id_super_ = value;
  // @@protoc_insertion_point(field_set:PrivateProto.RegVerifiedAccountToGateway.login_id_super)
}

// -------------------------------------------------------------------

// ZoneGatewayReady

// required uint64 acc_id = 1;
inline bool ZoneGatewayReady::has_acc_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ZoneGatewayReady::set_has_acc_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ZoneGatewayReady::clear_has_acc_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ZoneGatewayReady::clear_acc_id() {
  acc_id_ = GOOGLE_ULONGLONG(0);
  clear_has_acc_id();
}
inline ::google::protobuf::uint64 ZoneGatewayReady::acc_id() const {
  // @@protoc_insertion_point(field_get:PrivateProto.ZoneGatewayReady.acc_id)
  return acc_id_;
}
inline void ZoneGatewayReady::set_acc_id(::google::protobuf::uint64 value) {
  set_has_acc_id();
  acc_id_ = value;
  // @@protoc_insertion_point(field_set:PrivateProto.ZoneGatewayReady.acc_id)
}

// required uint64 login_id_super = 2;
inline bool ZoneGatewayReady::has_login_id_super() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ZoneGatewayReady::set_has_login_id_super() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ZoneGatewayReady::clear_has_login_id_super() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ZoneGatewayReady::clear_login_id_super() {
  login_id_super_ = GOOGLE_ULONGLONG(0);
  clear_has_login_id_super();
}
inline ::google::protobuf::uint64 ZoneGatewayReady::login_id_super() const {
  // @@protoc_insertion_point(field_get:PrivateProto.ZoneGatewayReady.login_id_super)
  return login_id_super_;
}
inline void ZoneGatewayReady::set_login_id_super(::google::protobuf::uint64 value) {
  set_has_login_id_super();
  login_id_super_ = value;
  // @@protoc_insertion_point(field_set:PrivateProto.ZoneGatewayReady.login_id_super)
}

// required uint64 token = 3;
inline bool ZoneGatewayReady::has_token() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ZoneGatewayReady::set_has_token() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ZoneGatewayReady::clear_has_token() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ZoneGatewayReady::clear_token() {
  token_ = GOOGLE_ULONGLONG(0);
  clear_has_token();
}
inline ::google::protobuf::uint64 ZoneGatewayReady::token() const {
  // @@protoc_insertion_point(field_get:PrivateProto.ZoneGatewayReady.token)
  return token_;
}
inline void ZoneGatewayReady::set_token(::google::protobuf::uint64 value) {
  set_has_token();
  token_ = value;
  // @@protoc_insertion_point(field_set:PrivateProto.ZoneGatewayReady.token)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PrivateProto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_super_2eproto__INCLUDED
